---
title: "Bleomycin self-limited model"
output: html_document
---

```{r}
library(Seurat)
library(dplyr)
library(Matrix)
```

```{r}
healthy1_1.data<-read.table(file=paste0("/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/","GSM3036808_Control_1_1_Mouse_lung_digital_gene_expression_400.dge.txt"), sep="", row.names = 1, header = TRUE, as.is = TRUE)
healthy1_1 <- CreateSeuratObject(counts = healthy1_1.data, project = "healthy1_1", min.cells = 3, min.features = 200)
healthy1_1$group <- "Healthy"

healthy1_2.data<-read.table(file=paste0("/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/","GSM3036809_Control_1_2_Mouse_lung_digital_gene_expression_1500.dge.txt"),sep="", row.names = 1, header = TRUE, as.is = TRUE)
healthy1_2 <- CreateSeuratObject(counts = healthy1_2.data, project = "healthy1_2", min.cells = 3, min.features = 200)
healthy1_2$group <- "Healthy"

healthy2.data<-read.table(file=paste0("/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/","GSM3036810_Control_2_Mouse_lung_digital_gene_expression_4000.dge.txt"),sep="", row.names = 1, header = TRUE, as.is = TRUE)
healthy2 <- CreateSeuratObject(counts = healthy2.data, project = "healthy2", min.cells = 3, min.features = 200)
healthy2$group <- "Healthy"

healthy3.data<-read.table(file=paste0("/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/","GSM3036811_Control_3_Mouse_lung_digital_gene_expression_6000.dge.txt"),sep="", row.names = 1, header = TRUE, as.is = TRUE)
healthy3 <- CreateSeuratObject(counts = healthy3.data, project = "healthy3", min.cells = 3, min.features = 200)
healthy3$group <- "Healthy"

healthy4.data<-read.table(file=paste0("/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/","GSM3036812_Control_4_Mouse_lung_digital_gene_expression_4000.dge.txt"),sep="", row.names = 1, header = TRUE, as.is = TRUE)
healthy4 <- CreateSeuratObject(counts = healthy4.data, project = "healthy4", min.cells = 3, min.features = 200)
healthy4$group <- "Healthy"

healthy5.data<-read.table(file=paste0("/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/","GSM3036813_Control_5_Mouse_lung_digital_gene_expression_4000.dge.txt"),sep="", row.names = 1, header = TRUE, as.is = TRUE)
healthy5 <- CreateSeuratObject(counts = healthy5.data, project = "healthy5", min.cells = 3, min.features = 200)
healthy5$group <- "Healthy"

healthy6.data<-read.table(file=paste0("/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/","GSM3036814_Control_6_Mouse_lung_digital_gene_expression_6000.dge.txt"),sep="", row.names = 1, header = TRUE, as.is = TRUE)
healthy6 <- CreateSeuratObject(counts = healthy6.data, project = "healthy6", min.cells = 3, min.features = 200)
healthy6$group <- "Healthy"
```

```{r}
integratedHealthy.seu <- merge(healthy1_1, y = c(healthy1_2, healthy2, healthy3, healthy4, healthy5, healthy6))
```

```{r}
bleo1.data<-read.table(file=paste0("/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/","GSM3036815_Bleo_1_Mouse_lung_digital_gene_expression_4000.dge.txt"),sep="", row.names = 1, header = TRUE, as.is = TRUE)
bleo1 <- CreateSeuratObject(counts = bleo1.data, project = "bleo1", min.cells = 3, min.features = 200)
bleo1$group = "Bleo"

bleo2.data<-read.table(file=paste0("/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/","GSM3036816_Bleo_2_Mouse_lung_digital_gene_expression_6000.dge.txt"),sep="", row.names = 1, header = TRUE, as.is = TRUE)
bleo2 <- CreateSeuratObject(counts = bleo2.data, project = "bleo2", min.cells = 3, min.features = 200)
bleo2$group = "Bleo"

bleo3.data<-read.table(file=paste0("/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/","GSM3036817_Bleo_3_Mouse_lung_digital_gene_expression_6000.dge.txt"),sep="", row.names = 1, header = TRUE, as.is = TRUE)
bleo3 <- CreateSeuratObject(counts = bleo3.data, project = "bleo3", min.cells = 3, min.features = 200)
bleo3$group = "Bleo"
```

```{r}
integratedBleo.seu <- merge(bleo1, y = c(bleo2, bleo3))
```

```{r}
bleoInt <- merge(integratedHealthy.seu, y = c(integratedBleo.seu))
```

```{r}
bleoInt[["percent.mt"]] <- PercentageFeatureSet(bleoInt, pattern = "^MT-")
bleoInt <- subset(bleoInt, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
bleoInt <- SCTransform(bleoInt, vars.to.regress = "percent.mt", verbose = FALSE)
```

```{r}
bleoInt <- NormalizeData(bleoInt)
bleoInt <- FindVariableFeatures(bleoInt, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(bleoInt)
bleoInt <- ScaleData(bleoInt, features = all.genes)
```

```{r}
bleoInt <- RunPCA(bleoInt)
bleoInt <- FindNeighbors(bleoInt, dims= 1:10)
bleoInt <- FindClusters(bleoInt, resolution = 0.5)
bleoInt <- RunTSNE(bleoInt)
```


```{r}
DimPlot(bleoInt, reduction = "tsne", group.by = "group")
```

```{r}
library(SingleR)
library(scater)
library(scRNAseq)
```

```{r}
immGen <- ImmGenData()
bleoSC <- as.SingleCellExperiment(bleoInt)
bleoSC <- logNormCounts(bleoSC)
pred.bleoSC <- SingleR(test = bleoSC, ref = immGen, labels = immGen$label.main)
pred.bleoSCfine <- SingleR(test = bleoSC, ref = immGen, labels = immGen$label.fine)
#pred.bleoSCfine
#pred.bleoSC
```

```{r}
#general annotation
table(pred.bleoSC$labels)
bleoInt[["SingleR.labels"]]<- pred.bleoSC$labels
new.cluster.ids <- c("B cells", "B cells, pro", "Basophils", "DC", "Endothelial cells", "Eosinophils", "Epithelial cells", "Fibroblasts", "ILC", "Macrophages", "Mast cells", "Microglia", "Monocytes", "justMacs", "NK cells", "NKT", "Stem cells", "Stromal cells", "T cells", "Tgd" )
names(new.cluster.ids) <- levels(bleoInt)
```

```{r}
#fine annotation
table(pred.bleoSCfine$labels)
bleoInt[["SingleR.labels"]]<- pred.bleoSCfine$labels
new.cluster.ids <- c("B cells", "B cells, pro", "Basophils", "DC", "Endothelial cells", "Eosinophils", "Epithelial cells", "Fibroblasts", "ILC", "Macrophages", "Mast cells", "Microglia", "Monocytes", "justMacs", "NK cells", "NKT", "Stem cells", "Stromal cells", "T cells", "Tgd" )
names(new.cluster.ids) <- levels(bleoInt)
```

```{r}
allBleoMacs <- bleoInt[,bleoInt$SingleR.labels == "Macrophages"]
someBleoMacs <- bleoInt[,bleoInt$SingleR.labels == "Macrophages (MF.ALV)"]
```

```{r}
allBleoMacs[["percent.mt"]] <- PercentageFeatureSet(allBleoMacs, pattern = "^MT-")
allBleoMacs <- subset(allBleoMacs, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

someBleoMacs[["percent.mt"]] <- PercentageFeatureSet(someBleoMacs, pattern = "^MT-")
someBleoMacs <- subset(someBleoMacs, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
```


```{r}
#adjust object for general/fine annotation
TSNEPlot(allBleoMacs, label = TRUE, pt.size = 0.5, group.by = "SingleR.labels") + NoLegend()
DimPlot(allBleoMacs, reduction = "tsne")
```

```{r}
allBleoMacs.markers <- FindAllMarkers(allBleoMacs, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, group.by = "group")
```

```{r}
allBleoMacs.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_logFC)
```

```{r}
VlnPlot(allBleoMacs, features = c("Fabp1", "Ear10"), group.by = "group")
```


```{r}
#shortcuts
saveRDS(integratedHealthy.seu, file = "/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/integratedHealthy.rds")
```
```{r}
saveRDS(integratedBleo.seu, file = "/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/integratedBleo.rds")
```
```{r}
saveRDS(bleoInt, file = "/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/bleoInt.rds")
```
```{r}
bleoInt <- readRDS(file = "/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/bleoInt.rds")
```

```{r}
saveRDS(allBleoMacs, file = "/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/allBleoMacs.rds")
```
```{r}
allBleoMacs <- readRDS(file = "/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/allBleoMacs.rds")
```
```{r}
saveRDS(someBleoMacs, file = "/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/someBleoMacs.rds")
```
```{r}
someBleoMacs <- readRDS(file = "/Users/liammagee/Desktop/R stuff/natureMacs/GSE111664_RAW/someBleoMacs.rds")
```